name: orthofinder

on:
  workflow_dispatch: # manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content
        with:
          ref: ${{ github.head_ref }}

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip wget
          pip3 install scipy

      - name: install orthofinder
        run: |
          wget https://github.com/davidemms/OrthoFinder/releases/download/2.5.5/OrthoFinder_source.tar.gz
          tar xzf OrthoFinder_source.tar.gz

      - name: run orthofinder
        run: |
          ulimit -n 4096
          python3 OrthoFinder_source/orthofinder.py -f pep/

      - name: upload results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: OrthoFinder results

